                    const rides = ["Choose...",
                     "Alice in Wonderland",
                     "Astro Orbitor",
                     "Autopia",
                     "Big Thunder Mountain",
                     "Buzz Lightyear Astro Blasters",
                     "Casey Jr. Circus Train",
                     "Chip 'n Dale Treehouse",
                     "Davy Crockett's Explorer Canoes",
                     "Disney and Pixar's Toy Story 4 Sneak Peek",
                     "Disneyland Monorail",
                     "Disneyland Railroad",
                     "Donald's Boat",
                     "Dumbo the Flying Elephant",
                     "Finding Nemo Submarine Voyage",
                     "Frontierland Shootin' Exposition",
                     "Gadget's Go Coaster",
                     "Goofy's Playhouse",
                     "Haunted Mansion",
                     "Hyperspace Mountain",
                     "Indiana Jones Adventure",
                     "It's a Small World",
                     "Jungle Cruise",
                     "King Arthur Carrousel",
                     "Mad Tea Party",
                     "Main Street Cinema",
                     "The Many Adventures of Winnie the Pooh",
                     "Mark Twain Riverboat",
                     "Matterhorn Bobsled",
                     "Peter Pan's Flight",
                     "Pirates of the Carribbean",
                     "Snow White's Scary Adventures",
                     "Splash Mountain",
                     "Star Tours - The Adventures Continue",
                     "Star Wars Launch Bay",
                     "Tarzan's Treehouse"]

                     export default rides